### PR TITLE
fix(ci): exempt the non-required m4pro bench check from auto-merge's failing scan

### PR DESCRIPTION
**Pull request by SJParthi**
## Summary

`auto-merge.yml`'s `ci-check` step refuses a merge when **any** check run on the PR head
carries a conclusion in `failure|cancelled|timed_out|action_required|stale`, exempting
exactly **one** name (`Auto-merge on green CI`). `m4pro-absolute-throughput` is a
**NON-required** self-hosted bench check — absent from `ci.yml`'s `ci-ok` `needs:` list
and absent from `branch-protection-drift.yml`'s 22 expected required contexts — yet a red
bench runner made that scan emit a `failing` row and **blocked every auto-merge
repo-wide**. This PR adds `m4pro-absolute-throughput` as the second exempt name, closing
the residual that DEC-PREMERGE-M4PRO-NONBLOCK-001 (MIGRATION.md #1753) had to scope away
in six separate honesty sites.

**ZERO `brutex/` source lines change.** `git diff --name-only origin/main...HEAD -- brutex/ rust/`
returns **0 files**. The whole diff is 6 files / +347 / -37: one awk conjunct plus a 15-line
WHY comment in a workflow, four carve-out comment lines, a comment-only rewrite in a shell
gate, hardened redteam pins, and three docs.

## Items completed

- [x] `.github/workflows/auto-merge.yml` — the `failing` awk scan gains a second exempt
      name; a 15-line comment records the non-required evidence, the #1753 lineage, and
      the deliberately narrow one-name scope. Four in-file comments that still asserted
      the pre-change absolute guarantee now carry the carve-out.
- [x] `scripts/ci/pre-merge-check.sh` — the round-3 SCOPE comment rewritten to record the
      amendment (the tolerance is now honoured **end-to-end**), with a corrected line
      cite. `NONBLOCKING_CHECK_NAMES` is byte-untouched.
- [x] `tests/redteam/test_redteam_automerge_safety.py` — pins that extract and execute the
      **real shipped** awk program via subprocess and — after the security lens
      demonstrated an evasion — **byte-freeze the whole program**.
- [x] `docs/MIGRATION.md` — new entry **#2254**; entry #1753 **appended** (never
      rewritten) with a SUPERSEDED-IN-PART note + two citation corrections.
- [x] `docs/MERGE_READINESS_GUARANTEE.md` — the normative charter reconciled at three
      sites (the correctness lens' MAJOR-1).
- [x] `CLAUDE.md` — three blurbs reconciled so no site still asserts the residual.

## Decision ID

**DEC-AUTOMERGE-M4PRO-NONBLOCK-002** (docs/MIGRATION.md entry **#2254**). Amends
**DEC-PREMERGE-M4PRO-NONBLOCK-001** (MIGRATION.md #1753), which fixed the sibling gate
`pre-merge-check.sh` but honestly scoped its claim to "THIS GATE's verdict only" because
the auto-merge scan upstream still refused.

---

## Scenarios covered

| Class | Scenario | Behaviour | Pinned by |
|---|---|---|---|
| Happy | all-green head, no m4pro row | `failing=[]` → merge proceeds; the new conjunct is evaluated **zero times** (POSIX `&&` short-circuit, probe-proven) | pre-existing 20 pins |
| Happy (the fix) | **CASE-A** — `failure` on `m4pro-absolute-throughput` only | `failing=[]` → merge proceeds (pre-fix: refused) | `test_redteam_automerge_safety.py` |
| Failure (fail-closed preserved) | **CASE-B** — `cancelled` m4pro **beside** `failure` on `Unit tests + coverage (100% gate)` | the REQUIRED check is **still reported** → merge refused | CASE-B pin |
| Edge | **CASE-C** — both exempt names failing | `failing=[]` (only the two named exemptions) | CASE-C pin |
| Edge (named residual) | **CASE-D** — `failure` on the sibling `bless-baseline` | **still blocks** — deliberately NON-exempt; operator authorization covers exactly one name | CASE-D pin |
| Edge | all five exempt-eligible conclusions (`failure`/`cancelled`/`timed_out`/`action_required`/`stale`) on m4pro | exempt in all five | 156-row differential |
| Edge | prefix / substring / case variants of the exempt name (e.g. `m4pro-absolute-throughput-2`, `M4PRO-...`) | **NOT** exempt — the match is exact `$2 != "..."`, re-verified under the runner's real **mawk 1.3.4** | security lens |
| Empty | zero check runs on the head | `failing=[]`, but the separate `CI OK (aggregate gate)` existence requirement still refuses — unchanged by this PR | pre-existing pin |
| Concurrent | two CI runs on one head (push + pull_request) | unchanged — the gate requires **every** `CI OK` instance to be `success` (DEC-AUTOMERGE-ALLGREEN-001) | untouched code path |
| Adversarial | a future regex-shaped exemption (`$2 !~ /^(Unit tests\|CodeQL)/`) that would exempt arbitrary REQUIRED checks | **FAILS** the frozen-program assert (executed) | `EXPECTED_FAILING_AWK_PROGRAM` |

## Failure modes

| Failure | What the system does | Why that is right |
|---|---|---|
| m4pro red / cancelled / timed out | auto-merge **proceeds**; the red bench check stays visible in the checks UI | the check is provably non-required (MIGRATION.md #382 + #1534): a bench regression is caught POST-merge as a red run + issue, never as a merge blocker |
| any REQUIRED check red | auto-merge **refuses**, naming the check | fail-closed is preserved — CASE-B is the executed proof |
| `bless-baseline` red | auto-merge **refuses** | the named residual of #1753, narrowed but not eliminated; widening it needs its own DEC |
| the workflow's awk is later widened (third name, OR-collapse, regex form) | **red CI** naming it, via the byte-frozen program assert | a silent gate weakening is structurally impossible |
| a job is renamed so the extractor's anchor vanishes | the pin **fails loudly** (both extractors assert the shape they found) | never a silently-passing ghost string |
| `git revert` of this PR | the two new pins fail **by design** and must be reverted with it | recorded in #2254 so a future reverter is not surprised |
| check-run name containing a tab | already neutralised upstream by `jq @tsv` | verified by the security lens; unchanged by this PR |

## Real-run proof

Every command below was executed; counts are captured, not estimated.

- `pytest -q tests/redteam/test_redteam_automerge_safety.py` — **22 passed**
- `pytest -q tests/redteam/test_redteam_premerge_guard.py` — **29 passed, UNMODIFIED**
- `pytest -q tests/unit/test_claude_md_branch_consistency.py` — **10 passed**
- `ruff check` — clean; `ruff format --check` — clean
- `mypy --strict` — **0 new** (the pre-existing `yaml` stub error proven by stashing the
  file and re-running against the baseline: identical error, line shift only)
- `bash -n scripts/ci/pre-merge-check.sh` — clean; all three workflows `yaml.safe_load`
- `.venv/bin/python scripts/ci/validate_ledger_numbering.py` — green, **1541 unique headers**
- `.venv/bin/python scripts/ci/validate_citation_accuracy.py` — every citation accurate
- **Fails-before:** with ONLY the workflow reverted to origin/main → **2 failed / 20 passed**
  (specificity, not vacuity)
- **Evasion proof:** the demonstrated regex-exemption **FAILS** the frozen-program assert
- **Measured perf:** old-vs-new awk over a realistic 42-row check set, 300 reps —
  **0.599 s vs 0.608 s** (1.5 %, inside noise)
- **Differential:** 156-row old-vs-new comparison — divergences are **exactly** the 5
  m4pro conclusions, zero others
- **LIVE, on this very PR:** while this PR's own CI ran, `m4pro-absolute-throughput` went
  `failure` on this head SHA (CheckRunID `89665808948`). The exact latent blocker this PR
  fixes armed itself on the PR that fixes it.

## Rollback plan

`git revert` the two commits (`3a3e617` then `4240996`) — that restores the single-conjunct
awk and the pre-change comments. The two NEW redteam pins then fail **by design** (they
assert the exemption exists) and MUST be reverted in the same commit; this coupling is
recorded in MIGRATION.md #2254 so a future reverter is not surprised. Nothing else needs
undoing: no `brutex/` source, no schema, no stored bytes, no run identity, no lake, no
frozen golden is touched, so there is no data migration to reverse. `NONBLOCKING_CHECK_NAMES`
in `pre-merge-check.sh` is byte-untouched, so #1753's sibling behaviour survives a revert
of this PR intact.

## Out of scope

- **`bless-baseline`** — the sibling self-hosted bench job stays NON-exempt. The operator
  authorization covers exactly `m4pro-absolute-throughput`; widening it requires its own DEC.
- **Flipping the m4pro check to required, or deleting it** — explicitly on the do-not-touch
  list; this PR only stops it from blocking merges.
- **Any bench ceiling change** — never widened to make a run green (Golden Rule #10).
- **`tests/bench/test_pull_at_scale_gate.py`, the `typos` job, `bench-m4pro.yml`** —
  untouched, per the standing do-not-touch list.
- **The `lru_cache` micro-optimisation** on `_ci_check_failing_awk_program` (~140 ms) —
  **declined**: it would diverge from 14 pre-existing unmemoised call sites in the same
  file and does not justify a CI lap on its own.
- **A live auto-merge that actually fires while m4pro is red** — that is the post-merge
  proof, honestly deferred (see Honest envelope).

---

## Z+ 15-row matrix (100% everything — charter §C)

| Demand | This PR's proof | Real-time check |
|---|---|---|
| 100% code coverage | N/A for `brutex/` — `git diff --name-only origin/main...HEAD -- brutex/ rust/` returns **0 files**. The touched code is a test file; the rest is a workflow, a shell comment, and docs. | `scripts/ci/coverage_gate_discovery.py` (untouched, green) |
| 100% audit coverage | Recorded as MIGRATION.md **#2254**; ledger validator green (**1541 headers, all unique**). No runtime action added, so no audit-JSONL emitter applies. | `validate_ledger_numbering.py` |
| 100% testing coverage | **61 passed** across the three affected suites (22 automerge redteam, 29 premerge-guard UNMODIFIED, 10 claude_md consistency). Golden/bench/property/stress: N/A — no engine, lake, or hot path touched. | `pytest -q tests/redteam tests/unit/test_claude_md_branch_consistency.py` |
| 100% code checks | ruff + ruff-format clean; `mypy --strict` **0 new** (baseline-diff proven); all three workflows `yaml.safe_load`; `bash -n` clean. | pre-push hooks + ci.yml type job |
| 100% code performance | Measured old-vs-new awk, 42-row set, 300 reps: **0.599 s vs 0.608 s**. `&&` short-circuits — probe-proven the new conjunct costs **zero** on an all-green head. | hot-path lens, measured |
| 100% monitoring | N/A — no runtime component. The gate's decision is already echoed in the workflow log (`failing=[...]`). | workflow run log |
| 100% logging | N/A — no `structlog` surface; awk prints the offending `name = conclusion` rows verbatim, unchanged. | workflow run log |
| 100% alerting | N/A — a blocked merge is already surfaced by the check-run UI. | GitHub checks UI |
| 100% security | The change **narrows nothing that was protecting anything**: the exempted check is provably non-required. Every required check still blocks — pinned. Zero secrets, zero `permissions:` change, zero new network egress; `jq @tsv` already neutralises tab injection in check-run names. | `branch-protection-drift.yml` |
| 100% security hardening | The exemption is a **name filter**, not a short-circuit — **and the whole awk program is byte-frozen**. The security lens DEMONSTRATED that a per-name census is evadable by a regex conjunct exempting arbitrary REQUIRED checks; root fix = `EXPECTED_FAILING_AWK_PROGRAM` freezes the program whitespace-normalised, so no regex form, no `index()`/`substr()`, no `system()`/`getline` can enter this fail-closed gate without a red test naming it. **The demonstrated evasion now FAILS the frozen assert (executed).** | `pytest tests/redteam/test_redteam_automerge_safety.py` |
| 100% bug fixing | Fails-before executed: pre-fix awk on CASE-A yields `failing=[m4pro-absolute-throughput = failure]` → refused; post-fix `failing=[]`. Re-proven after the fix round: workflow-only revert → **2 failed / 20 passed**. | 4-agent review below |
| 100% scenarios covering | See **Scenarios covered** — 10 enumerated classes, each with its pin; plus the 156-row differential and the real-mawk re-run. | the hardened pins |
| 100% functionalities covering | All three helpers (`_ci_check_failing_awk_program`, `_bless_baseline_check_run_name`, `_run_failing_scan`) are exercised; both extractors assert the shape they found, so a workflow reshape or job rename fails loudly. | `pytest -q` |
| 100% code review | 4-agent hostile review below (hot-path / security / correctness / cite-path) — **SHIP / SHIP / FIX-FIRST / SHIP**, every confirmed finding landed. | that section |
| 100% extreme check | Fails-before for the **pins themselves**: with ONLY the workflow reverted, both new pins FAIL and all 20 pre-existing pins PASS. The correctness lens proved non-vacuity four separate ways and verified #1753's ledger entry is byte-preserved under this change's append (`new.startswith(old)` → True, executed). | `git show origin/main:...` + `pytest` |

## Z+ 7-row resilience matrix (charter §C)

| Demand | Honest envelope | This PR's proof |
|---|---|---|
| Zero ticks lost | N/A — CI-config change; no data path, no ingest, no lake write. | 0 files under `brutex/`/`rust/` |
| WS never disconnects | N/A — no WebSocket in Track 1 (DEC-LIVE-REMOVE-001). | confirmed |
| Never slow/locked/hanged | The awk scan is O(check runs) per merge attempt, **unchanged** — 2 extra string compares per already-failing row, no allocation, program compiled once. | measured 0.599 s → 0.608 s / 300 reps |
| QuestDB never fails | N/A — BruteX uses DuckDB + Parquet + LMDB. | confirmed |
| O(1) latency | O(1) additional work per row and **zero** on green rows (short-circuit, probe-proven). No engine/lake/hot-path byte changed, so every existing O(1) bench gate is untouched and still green. | hot-path lens, measured |
| Uniqueness + dedup | Ledger uniqueness preserved: **1541 headers, all unique**; #2254 collides with nothing. | `validate_ledger_numbering.py` |
| Real-time proof | **LIVE**: `m4pro-absolute-throughput` went `failure` on this head SHA (CheckRunID `89665808948`) while this PR's CI ran — the latent blocker armed itself on the PR that fixes it, and is tolerated **by design**. | this PR's check-run list |

## Z+ 7-layer audit

| Layer | This PR's status |
|---|---|
| DETECT | The pins fail the instant the exemption is removed, the exempt set grows/shrinks, the scan is collapsed to an OR, **or any character of the awk program changes**. Fails-before proven by reverting ONLY the workflow (2 failed / 20 passed). |
| VERIFY | Four executed probe cases (A/B/C/D) driven through the **real extracted** awk program via `subprocess`; the correctness lens' 156-row old-vs-new differential; the security lens' re-run under the runner's actual **mawk 1.3.4**. |
| RECONCILE | MIGRATION.md #1753 **appended**, never rewritten (byte-preservation executed-verified). **Six** honesty sites reconciled: three CLAUDE.md blurbs, the `pre-merge-check.sh` SCOPE comment, #1753 itself, and the normative charter `docs/MERGE_READINESS_GUARANTEE.md` at three sites. Four in-file workflow comments now carry the carve-out. |
| PREVENT | The **whole awk program is byte-frozen** (`EXPECTED_FAILING_AWK_PROGRAM`), so a future widening — a third name, an OR-collapse, or a regex-shaped exemption of REQUIRED checks — is a red CI naming it. The exempt-name census is kept as the precise diagnostic, its docstring rewritten to state its own honest limit. |
| AUDIT | MIGRATION.md **#2254** (full ROOT / FIX / HONEST envelope / PROOF / TESTS / GATES structure + the 4-agent fix-round clause) and the ledger validator. |
| RECOVER | See **Rollback plan** — `git revert` restores the single-conjunct awk; the two new pins must be reverted with it, and that coupling is recorded in #2254. |
| COOLDOWN | CI-config + redteam test + docs only; zero `brutex/` source. No soak needed. The first real-world proof is the next auto-merge that fires while the m4pro runner is red. |

## 4-agent hostile review

Four `hostile-reviewer` agents run in parallel against commit `3a3e617b`, each read-only,
each required to carry executed evidence for every claim. The fix round is commit
`4240996a`; the workflow's **executable** region is byte-identical to the reviewed commit
(only comment lines changed there — verified by diffing with comment lines filtered out).

| Agent | Lens | Findings | Severity |
|---|---|---|---|
| Hot-path | perf + O(1) + allocation | Zero `brutex/`/`rust/` files touched; no runtime consumer of the two CI files. awk `&&` short-circuits (probe-proven) → the new conjunct costs **zero** on green rows; 0.599 s vs 0.608 s over 300 reps. One optional NIT: the pins re-parse the 35 KB workflow YAML per call (~140 ms) — matches 14 pre-existing unmemoised call sites in the same file and is 0.8 % of the redteam suite; **declined** with that reason recorded. | **0 BLOCKER / 0 MAJOR / 0 MINOR / 1 NIT — SHIP** |
| Security | secrets + injection + supply-chain + gate-weakening | Verified under the runner's real **mawk 1.3.4** that the exemption is exact (no prefix/substring/case leak), fail-closed preserved, zero secrets / `permissions:` / egress touched, `jq @tsv` neutralises tab injection. **MINOR-1 — DEMONSTRATED an evasion of the exempt-name census** (a regex conjunct exempting arbitrary REQUIRED checks while census and OR-guard both stay green) → **fixed at root** by byte-freezing the program; the evasion now fails the frozen assert (executed). **MINOR-2** — the `bless-baseline` residual pin asserted a JOB ID, not the check-run name GitHub emits → fixed by asserting **both**, the real one **derived** from `bench-m4pro.yml` so a rename fails loudly. + 5 citation NITs, all landed. | **0 BLOCKER / 0 MAJOR / 2 MINOR / 5 NIT — SHIP (both MINORs fixed)** |
| Correctness | race + edge-trigger + false-OK + test honesty | Proved the pins non-vacuous four separate ways; verified #1753's ledger entry byte-preserved (`new.startswith(old)` → True); confirmed the 156-row differential diverges on exactly the 5 m4pro conclusions. **MAJOR-1**: the **normative charter** `docs/MERGE_READINESS_GUARANTEE.md` — the doc CLAUDE.md Rule 13 binds every PR to, and the only place the property is a *guarantee* rather than a comment — still asserted the absolute "ANY failing check run refuses" at three sites → **fixed**, all three now name the exempted non-required check and cite both DECs; the census is six sites, not five. **MINOR-1**: three comments *inside the edited workflow* (+ one already made false by #1753) asserted the same absolute property → **fixed**, all four carry the carve-out. + NIT-2 (`-F` TAB vs `-F'\t'`, identical under mawk) documented in the helper docstring. | **0 BLOCKER / 1 MAJOR / 1 MINOR / 2 NIT — FIX-FIRST (all landed)** |
| Cite/path | every cited path + symbol + line + decision ID verified | Every path, symbol, DEC-ID and ledger number resolves. Independently confirmed the security lens' citation drift: the `failing` awk scan is at **290-291** pre-change / **305-308** after (the earlier 287-291 / 305-309 spanned two *different* anchors); the premerge-guard suite is **29** tests, not the 26 inherited from #1753's era. + the PR #1754 "72 check runs" observation now carries #1753's own "coordinator-reported, NOT locally re-derivable" hedge. All corrections landed at every cite site. | **0 BLOCKER / 0 MAJOR / 2 MINOR / 3 NIT — SHIP** |

---

## Honest envelope (Golden Rule #10)

- **REAL:**
  - The defect is real and was **executed-reproduced**: pre-fix awk on a failed-m4pro row
    emits `failing=[m4pro-absolute-throughput = failure]`.
  - `m4pro-absolute-throughput` is provably **non-required** — absent from `ci.yml`'s
    `ci-ok` `needs:` and from `branch-protection-drift.yml`'s expected contexts.
  - Fail-closed is preserved: a required check failing **beside** a red m4pro is still
    reported (CASE-B), and `bless-baseline` still blocks (CASE-D).
  - The pins are **non-vacuous** — reverting only the workflow fails both while all 20
    pre-existing pins pass.
  - The **demonstrated** census evasion is closed at root by the frozen program, and the
    evasion's failure under the new assert was **executed**, not argued.
  - Zero `brutex/` source lines changed.
- **PARTIAL:**
  - The exemption is **one name only**. `bless-baseline` is deliberately still blocking.
    #1753's named residual (an operator-cancelled bench run) is narrowed, not eliminated,
    and remains recorded.
  - The fix is proven by **executed probe cases + a 156-row differential + a real-mawk
    re-run**, not by a live auto-merge that actually fired while m4pro was red. That is
    the post-merge proof, honestly deferred.
  - The "72 check runs on #1754's head carried no m4pro entry" observation is
    **coordinator-reported context**, not locally re-derivable in this environment
    (no `gh` on PATH) — the same hedge #1753 applied to its own incident citation.
- **ROADMAP:**
  - The optional `lru_cache` micro-optimisation is not taken (see **Out of scope**).

Anti-pattern check: every claim above cites a real file path / line / test / CheckRunID.
No claim rests on a hypothetical artifact. Verified by the 4-agent cite/path lens.

## Test plan

- [x] `ruff check` — clean; `ruff format --check` — clean
- [x] `mypy --strict` — **0 new** (pre-existing `yaml` stub error, proven by baseline diff)
- [x] `pytest -q tests/redteam/test_redteam_automerge_safety.py` — **22 passed**
- [x] `pytest -q tests/redteam/test_redteam_premerge_guard.py` — **29 passed, UNMODIFIED**
- [x] `pytest -q tests/unit/test_claude_md_branch_consistency.py` — **10 passed**
- [x] `bash -n scripts/ci/pre-merge-check.sh` — clean; all three workflows `yaml.safe_load`
- [x] `.venv/bin/python scripts/ci/validate_ledger_numbering.py` — green, 1541 unique headers
- [x] `.venv/bin/python scripts/ci/validate_citation_accuracy.py` — every citation accurate
- [x] Fails-before: workflow-only revert → **2 failed / 20 passed**
- [x] Evasion proof: the demonstrated regex-exemption **FAILS** the frozen-program assert

---

_Body revision note: this revision adds the five Definition-of-Ready plan-first sections
(Scenarios covered / Failure modes / Real-run proof / Rollback plan / Out of scope) that
`scripts/ci/definition-of-ready-guard.sh` requires. The prior revision's narrative is
retained in GitHub's body edit history; the durable record is MIGRATION.md #2254._

---

🤖 Generated with [Claude Code](https://claude.com/claude-code)

https://claude.ai/code/session_012jcgXiSZGf7prPqTe2iMvU

### CODE REVIEW

**Comment by SJParthi** [comment]
## `Benchmarks (O(1) NFR gates)` is RED — diagnosed as a shared-runner flake, not a regression

Recording the evidence before any re-run, so this is not a blind re-trigger.

### The failure

Run [30159123244](https://github.com/SJParthi/bruteX/actions/runs/30159123244), job `89681526716`:

```
FAILED tests/bench/test_pull_at_scale_gate.py::test_pull_at_scale_gate_saturates_allowed_rate
AssertionError: rps_1s_max 18 ran away past ceiling 8.0 + burst 1 + tol 3
assert 18 <= ((8.0 + 1) + 3)
achieved_rps=7.875, physical_call_rps=7.875, allowed_rps_timeavg=8.0, slack_rps=0.125,
write_p99_ms=323.886, physical_calls=520, bars_appended=48000, windows=520, wall_s=66.0355, seed=20260626
1 failed, 442 passed, 15 skipped in 574.51s
```

### Why this is non-deterministic, not a code defect

**1. The identical tree passed.** Run [30158555589](https://github.com/SJParthi/bruteX/actions/runs/30158555589), job `89679998828` — same workflow, same job name, and the **same `head_sha` `4240996a53d3b3b680fa1b051182044f2478df7d`** — completed `conclusion: success`, with its `pytest benchmarks` step green (12:52:11Z → 13:03:38Z). That run was later `cancelled` as superseded, but the bench job had already finished green on its own.

Same commit, same job, one pass and one fail ⇒ the outcome is not a function of this branch's tree.

**2. This branch cannot reach the code under test.** `git diff --stat origin/main...HEAD` is 6 files:

| file |
|---|
| `.github/workflows/auto-merge.yml` |
| `CLAUDE.md` |
| `docs/MERGE_READINESS_GUARANTEE.md` |
| `docs/MIGRATION.md` |
| `scripts/ci/pre-merge-check.sh` |
| `tests/redteam/test_redteam_automerge_safety.py` |

**Zero `brutex/` source files.** Nothing matching `bench|rate`. There is no path from this diff to the rate controller, the token bucket, or the write path the assertion measures.

**3. The reported numbers name the mechanism.** `write_p99_ms=323.886` on a shared 2-core runner. A long write stall lets the rate controller's token bucket accumulate; when the stall clears, the queued calls fire inside a single 1-second window — so `rps_1s_max` spikes to 18 while the **time-average stayed correct**: `achieved_rps=7.875 ≤ allowed_rps_timeavg=8.0`, `slack_rps=0.125`. The controller never over-issued; the 1-second bucketing observed the drain burst. This is the shared-runner I/O-jitter class, not a pacing regression.

### What I am NOT doing

- **Not widening the ceiling / burst / tolerance.** The CI annotation on this job states it verbatim: *"Ratio ceilings live in `tests/bench/_o1_tiers.py`; never widen one to make a run green (Golden Rule #10)."*
- **Not touching `tests/bench/test_pull_at_scale_gate.py`.** It is on the do-not-touch list.
- **Not re-running blind.** The root cause is measured above; the re-run is justified by the same-`head_sha` pass, not by hope.

### Next step

Three jobs on run 30159123244 are still `in_progress` (`Unit test shard 3`, `Python mutation (mutmut)`, `Per-module coverage gates (static list)`). GitHub refuses `rerun_failed_jobs` while a run is in flight, so I will re-run the single failed bench job once the run completes, then merge on green.

If the same assertion fails again on an unchanged tree, that changes the diagnosis from "runner jitter" to "the 1-second-bucket observable is under-specified for a stalling writer" — which is a real gate-design finding and would get its own DEC rather than a tolerance bump. I will report either outcome here.

---
_Generated by [Claude Code](https://claude.ai/code)_

**Comment by SJParthi** [comment]
**Correction to my previous comment, plus current status.**

In [comment 5078699039](https://github.com/SJParthi/bruteX/pull/1756#issuecomment-5078699039) I described `Unit test shard 3 (coverage data)` as *"a genuine outlier"* on the grounds that its sibling shards finished in 1:36–25:37. **That framing was wrong and I am retracting it.** I had no baseline when I wrote it; I have one now.

Measured on run [`30147258571`](https://github.com/SJParthi/bruteX/actions/runs/30147258571) — a **`success`** run on **`main`**:

| job | duration | conclusion |
|---|---|---|
| Unit test shard 0 | 1.52 min | success |
| Unit test shard 1 | 13.12 min | success |
| Unit test shard 2 | 20.85 min | success |
| **Unit test shard 3** | **86.70 min** | **success** |
| Unit test shard 4 | 26.02 min | success |
| Unit test shard 5 | 21.15 min | success |

Shard 3 is the repo's **longest job by design** — 86.70 min on a fully green run, with the next-longest job at 49.53 min (`Per-module coverage gates`). The shard split is simply uneven; nothing is hanging. `ci.yml:378` sets `timeout-minutes: 130`, so 86.7 min sits comfortably inside the budget.

**So this PR is not blocked on a defect.** As of 14:26Z, run `30159123244` stands at **58 success / 1 failure / 1 in_progress**, and the one `in_progress` job is shard 3 at ~74 min — inside the baseline, not past it. Hard limit ≈ 15:22Z.

The single failure is unchanged and still the flake I documented:

```
FAILED tests/bench/test_pull_at_scale_gate.py::test_pull_at_scale_gate_saturates_allowed_rate
AssertionError: rps_1s_max 18 ran away past ceiling 8.0 + burst 1 + tol 3
achieved_rps=7.875, allowed_rps_timeavg=8.0, write_p99_ms=323.886, seed=20260626
```

The corroborating evidence also stands, with one honesty note attached to it: the bench job **`89679998828`** completed **`success` in 12:57 on this identical `head_sha`**, so the same tree passes this gate. That job belonged to run `30158555589`, which was **CANCELLED partway** (6 cancelled jobs plus a `Definition of Ready` failure) — so it was *not* a full green run and I am not presenting it as one. The bench job's own completion is the evidence; the run around it is not.

Plan unchanged: GitHub refuses `rerun_failed_jobs` while a run is in flight, so I will re-run the one failed bench job once shard 3 lands, then merge on green.

If that bench assertion fails a **second** time on this unchanged tree, I will not touch the ceiling. The pre-committed reading applies instead: the 1-second-bucket observable is under-specified for a stalling writer — a long write stall lets the token bucket accumulate, so queued calls fire inside one 1-second window and `rps_1s_max` spikes while `allowed_rps_timeavg` stays exactly at the 8.0 ceiling (which it does: 7.875 achieved). That is a **gate-design** finding needing its own DEC, not a tolerance bump (CLAUDE.md Golden Rule #10).

---
_Generated by [Claude Code](https://claude.ai/code)_
